
version: '3.4'

services:
  hassioannounce:
    image: hassioannounce
    build:
      context: .
      dockerfile: hassio-announce/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
